import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Time from '../components/Drawdown/Time';
import Rate from '../components/Drawdown/Rate';
import Income from '../components/Drawdown/Income';

import Footer from '../components/Footer';



const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        {/* <Breadcrumbs /> */}
      </header>

      <main className={styles.main}>
        <Time />
        <Rate />
        <Income />
      </main>

      <Footer />
    </div>
  )
}

export default Home
